### ISSUE TITLE
sst failed: Error writing file 'UNKNOWN' (errno: 32 "Broken pipe")

### ISSUE THREAD

**Issue by wilsonliu78** [MariaDB/mariadb-docker#293] opened 2020-04-06 12:17 UTC
when SST take a long time, it will failed. 

refer official instructions(https://mariadb.com/kb/en/library/systemd/#ssts-and-systemd), modify systemd TimeoutStartUSec, 

but docker cmd not use systemd , it don't work!!

Any body can help?

**Comment by wglambert** [comment] 2020-04-06 16:31
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue?

**Comment by grooverdan** [comment] 2020-08-12 01:32
With version of mariadb used, no logs or the sst mechanism there is no chance of us resolving this for you. Please ask on [DBA Stack Exchange](https://dba.stackexchange.com/) with details or use a professional service provider.

**Comment by grooverdan** [comment] 2021-03-02 00:24
closing due to lack of information.

**Closed by grooverdan** 2021-03-02 00:24 UTC

**Comment by hcl3039359** [comment] 2022-01-21 03:20
Have you solved it? I have encountered the same problem

**Comment by grooverdan** [comment] 2022-01-21 03:30
Include the donor and joiner logs from the before the SST started until after the error, the galera and mariadb versions used, how the cluster was started, and the mariadb configuration, and it might be possible to derive an answer. Without that there are too many possibilities to attempt to enumerate.
