### ISSUE TITLE
[issue] entrypoint script does not escape password properly

### ISSUE THREAD

**Issue by Celmor** [MariaDB/mariadb-docker#183] opened 2018-07-15 21:05 UTC
Type                                | Version/Name
  ---                                  |     --- 
MARIADB_VERSION     | 1:10.3.8+maria~jessie
Docker Image                 | mariadb:10.3.8@sha256:f2085c2176ba6294cf73033b344a420faa2ddae1b97b6795c101552e86284ba3
Docker Hosts Kernel Version | 4.17.0-2-MANJARO
Docker Server Version | 18.05.0-ce

# Description
I've generated my password for `MYSQL_ROOT_PASSWORD` env var with keepass with all character ranges enabled. The container exits with
``` 
ERROR 1064 (42000) at line 6: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Oe(]xI=<&(') ;
GRANT ALL ON *.* TO 'root'@'localhost' WITH GRANT OPTION ;
CREATE' at line 1
```
[Full log](https://pastebin.com/raw/QHYJxa01)
where `'Oe(]xI=<&(` was part of my `MYSQL_ROOT_PASSWORD`.

# Steps to reproduce
Run `sudo docker run --rm -e "MYSQL_ROOT_PASSWORD='Oe(]xI=<&(" mariadb:10.3.8@sha256:f2085c2176ba6294cf73033b344a420faa2ddae1b97b6795c101552e86284ba3`

**Comment by yosifkit** [comment] 2018-07-16 19:53
We don't escape any password characters since we didn't want to implement the equivalent of `mysql_real_escape_string` in bash and didn't want to burden the image with an install of a library/language just for this purpose.

https://github.com/docker-library/mariadb/blob/8818681187395ecf968ab61dfd8d04d458c356dc/docker-entrypoint.sh#L130

**Comment by Celmor** [comment] 2018-07-16 21:33
@yosifkit Then the fact passwords won't be escaped (and have to be chosen appropriately) should be documented on the [Docker Hub page](https://hub.docker.com/_/mariadb/).

**Comment by tianon** [comment] 2018-09-05 20:34
This is essentially a duplicate of https://github.com/docker-library/mysql/issues/338.

@ltangvald what're your thoughts?  For `postgres`, we recently applied https://github.com/docker-library/postgres/pull/489, which allowed us to pass variables directly to `psql` so that the user input could be properly escaped by `psql` itself -- does there already exist any similar method in `mysql` for implementing something like that which I'm not familiar with (and can't seem to find)? :pray:  (Maybe something like that on the roadmap for the future? :sweat_smile:)

**Comment by ltangvald** [comment] 2018-09-06 06:28
I think printf %q should be enough, actually: https://github.com/mysql/mysql-server/blob/8.0/packaging/deb-in/mysql-packagesource-server.postinst.in#L86

**Comment by ltangvald** [comment] 2018-09-06 06:35
%q     ARGUMENT is printed in a format that  can  be  reused  as  shell
              input, escaping non-printable characters with the proposed POSIX
              $'' syntax.
This escapes certain symbols that don't need to be escaped in MySQL, such as $, but MySQL handles that, so if the root password is set to 'mypa$s', printf %q will output 'mypa\$s', but the password will still be stored as 'mypa$s'

**Comment by tianon** [comment] 2018-09-12 18:52
So, I don't think that'll work properly given that it outputs `$'...'` syntax sometimes:

```console
$ printf '%q\n' "$(echo -e 'a \r b \n c \\ d '\'' e " f \x1a g')"
$'a \r b \n c \\ d \' e " f \032 g'
```

(Which I don't think is valid in MySQL, right?)

**Comment by ltangvald** [comment] 2018-09-13 06:00
Does that work in postgres? i.e. setting the password to <pre>"$(echo -e 'a \r b \n c \\ d '\'' e " f \x1a g')"</pre>

**Comment by yosifkit** [comment] 2018-09-13 20:59
I got postgres to set the password without complaint but I can't get psql to authenticate using it in `PGPASSWORD`, so I am not sure which part failed (initial setting the password or using the password).

```bash
$ docker run -d -e POSTGRES_PASSWORD="$(echo -e 'a b \n c \\ d '\'' e " f \x1a g')" postgres:10
```

**Comment by ltangvald** [comment] 2018-09-14 05:46
Right, the same happens with our deb packages (that use printf %q). I'm not sure we should try to support _everything_, but random password generators often output some special characters that need escaping.

**Comment by grooverdan** [comment] 2021-03-05 04:53
Actually escaping isn't that bad. Only \ and ' need to be quoted and ensure the session (unlike my lazy test) SQL_MODE doesn't include NO_BACKSLASH_ESCAPES.

ref: https://mariadb.com/kb/en/string-literals/

<pre>
#!/bin/bash
set -eo pipefail
shopt -s nullglob

m="$HOME/repos/build-mariadb-server-10.5/client/mariadb -S /tmp/build-mariadb-server-10.5.sock"

$m -e "SET GLOBAL SQL_MODE = REPLACE(@@SQL_MODE, 'NO_BACKSLASH_ESCAPES', '');"
while [ 1 ]
do
	REAL_PASSWORD=$(pwgen   --numerals   --capitalize  --symbols --secure 32 1)
	#read -r -d '' -N 30 REAL_PASSWORD < /dev/urandom
	# SQL escaping \
	p=${REAL_PASSWORD//\\/\\\\}
	# SQL escaping '
	MARIADB_ROOT_PASSWORD=${p//\'/\\\'}
        $m <<- EOSQL || true
                      SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MARIADB_ROOT_PASSWORD}');
EOSQL
	echo "pass=${MARIADB_ROOT_PASSWORD}"
        $m  -u root -p"${REAL_PASSWORD}" -Be 'select 1' > /dev/null
done
<pre>

This cover all the pwgen characters that I saw after a while. Using /dev/urandom (the commented line) does however fail eventually on some character(s?) that I haven't got around to identifying (might even be a bug) - `--default-character-set=binary` didn't help.

If this is introduced now is this going to throw compatibility problems pre-escaping their password?

As a safe route, since no release has been done with 8e0175f1434c76218eba1a52acabbc196064aa88 I could start escaping the MARIADB_*_PASSWORD variables only on images going forwards and leave MYSQL_*_PASSWORD as is.

Any objection or other factors I should consider?

**Comment by mariadb-RoelVandePaar** [comment] 2021-03-08 09:14
Improved script
```
#!/bin/bash
set -eo pipefail
shopt -s nullglob

m="/test/MD060321-mariadb-10.6.0-linux-x86_64-dbg/bin/mariadb -uroot -S/test/MD060321-mariadb-10.6.0-linux-x86_64-dbg/socket.sock --force --binary-mode test"

$m -e "SET GLOBAL SQL_MODE = REPLACE(@@SQL_MODE, 'NO_BACKSLASH_ESCAPES', '');"
PREV_PWD=''
while true; do
  #REAL_PASSWORD=$(pwgen   --numerals   --capitalize  --symbols --secure 32 1)
  read -r -d '' -N 30 REAL_PASSWORD < /dev/urandom
  echo "REAL_PASSWORD=${REAL_PASSWORD}"; sync
  # SQL escaping \
  p=${REAL_PASSWORD//\\/\\\\}
  # SQL escaping '
  MARIADB_ROOT_PASSWORD=${p//\'/\\\'}
  echo "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"; sync
  $m -p"${PREV_PWD}" <<- EOSQL || true
   SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MARIADB_ROOT_PASSWORD}');
EOSQL
  echo "pass=${MARIADB_ROOT_PASSWORD}"; sync
  $m -p"${REAL_PASSWORD}" -Be 'SELECT 1;' > /dev/null
  PREV_PWD="${REAL_PASSWORD}"
done
```

**Comment by mariadb-RoelVandePaar** [comment] 2021-03-08 09:44
Also adding a write-to-file script for long runs.
```
#!/bin/bash
set -eo pipefail
shopt -s nullglob
set +H

m="/test/MD060321-mariadb-10.6.0-linux-x86_64-dbg/bin/mariadb -uroot -S/test/MD060321-mariadb-10.6.0-linux-x86_64-dbg/socket.sock --binary-mode test"

$m -e "SET GLOBAL SQL_MODE = REPLACE(@@SQL_MODE, 'NO_BACKSLASH_ESCAPES', '');"
PREV_PWD=''
FIRST_RUN=1
# Random entropy init
RANDOM=$(date +%s%N | cut -b10-19)
while true; do
  #REAL_PASSWORD=$(pwgen   --numerals   --capitalize  --symbols --secure 32 1)
  read -r -d '' -N 200 REAL_PASSWORD < /dev/urandom
  #echo "REAL_PASSWORD=${REAL_PASSWORD}"; sync 
  if [ -r pwd_done.txt ]; then
    mv pwd_done.txt pwd_done.prev
  fi
  echo "|||||${REAL_PASSWORD}|||||" > pwd_done.txt; sync
  # SQL escaping \
  p=${REAL_PASSWORD//\\/\\\\}
  # SQL escaping '
  MARIADB_ROOT_PASSWORD=${p//\'/\\\'}
  #echo "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"; sync
  if [ ${FIRST_RUN} -eq 1 -a -z "${PREV_PWD}" ]; then
    $m <<- EOSQL || exit 1
     SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MARIADB_ROOT_PASSWORD}');
EOSQL
  else
    $m -p"${PREV_PWD}" <<- EOSQL || exit 1
     SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${MARIADB_ROOT_PASSWORD}');
EOSQL
  fi
  FIRST_RUN=0
  #echo "pass=${MARIADB_ROOT_PASSWORD}"; sync
  $m -p"${REAL_PASSWORD}" -Be 'SELECT 1;' > /dev/null
  PREV_PWD="${REAL_PASSWORD}"
done
```

**Comment by mariadb-RoelVandePaar** [comment] 2021-03-09 08:22
An overnight run did not locate any issues using the script from my last comment.

**Comment by grooverdan** [comment] 2021-03-12 05:12
Thanks for testing @mariadb-RoelVandePaar.

For our users #356, contains what has passed my testing so far. If you'd like to test this and provide feedback this would be most useful.

**Closed** 2021-04-27 22:01 UTC
Labels: Issue
