### ISSUE TITLE
Server sent charset

### ISSUE THREAD

**Issue by PandemRus** [MariaDB/mariadb-docker#564] opened 2024-02-21 16:22 UTC

**Comment by LinuxJedi** [comment] 2024-02-21 16:50
@PandemRus there is no description here, but is this a duplicate of #560?

**Comment by grooverdan** [comment] 2024-02-22 01:09
Assuming so. @PandemRus please do put a bit more effort into a bug report. 3 words hardly qualifies as an actionable bug report.

**Closed by grooverdan** 2024-02-22 01:09 UTC
