### ISSUE TITLE
Latest Mariadb image has authentication issues

### ISSUE THREAD

**Issue by awptechnologies** [MariaDB/mariadb-docker#563] opened 2024-02-21 13:21 UTC
after updating image to the latest version with amd64 dae04d35ddd4 digest i had all kinds of authentication issues. downgrading to 11.2.3 fixed everything.

Every docker container i run that used maria db had authentication issues or a 500 http error. as soon as i reverted to 11.2.3 they all started with no errors. All data is good.

**Comment by lunarok** [comment] 2024-02-21 13:41
I confirmed, get the same effect here, this morning update has break any connexion to DB (official images of wordpress and nextcloud not connecting again with [Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host:

I did the same, use 11.3.2 image to revert back to a working DB

**Comment by Murazaki** [comment] 2024-02-21 13:45
Same as https://github.com/MariaDB/mariadb-docker/issues/560

It is a typo issue in config, that can be alleviated either by using prior versions or by overriding command parameters in docker-compose :
```
command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin 
```

**Comment by LinuxJedi** [comment] 2024-02-21 16:36
I'll close this as a duplicate of #560 for now, if you feel this is in error, please reopen it.

**Closed by LinuxJedi** 2024-02-21 16:36 UTC
